config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'convos#index'

  resources :users
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/yolo', to: 'sessions#create_for_test_user'
  get '/logout', to: 'sessions#destroy'

  get '/activity', to: 'users#show'
  get '/settings', to: 'users#edit'

  get '/about', to: 'static_pages#about'
  get '/tos', to: 'static_pages#tos'

  post '/poll/:poll_id/:id/vote', to: 'polls#vote', as: :vote_on_poll

  resources :topics

  get '/topics/:id/comments', to: 'topics#comments', as: :topic_comments


  resources :convos do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  get '/topics/:topic_slug/:id/:convo_slug', to: 'convos#show', as: :convo_slug

  get '/notifications', to: 'notifications#index'

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :convo
  belongs_to :user

  validates :user, presence: true
  validates :comment, presence: true

  before_save :handle_polls

  acts_as_tree

  acts_as_voteable
  include VoteActions
  include Report
  include PollsHandler

  scope :find_by_topic_id, lambda { |topic_id| joins(:convo).where('convos.topic_id = ?', topic_id) }

  def self.search(search)
    if search
      where("comment LIKE ?", "%#{search}%")
    else
      all
    end
  end

  def handle_polls
    polls_handler(comment)
  end

  def update_popularity
    if points == 0
        return 0
    end
    z = 1.281551565545 # 80% confidence
    n = upvotes + downvotes
    phat = 1.0*upvotes/n
    result = (phat + z*z/(2*n) - z * Math.sqrt((phat*(1-phat)+z*z/(4*n))/n))/(1+z*z/n)

    self.update_attribute(:weighted_score, result)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :report]
  
  invisible_captcha only: [:create, :update]

  def index
    @comments = 
      if params[:show] == 'popular'
        Comment.order('weighted_score DESC').page(params[:page]).per(25)
      else
        Comment.order('created_at DESC').page(params[:page]).per(25)
      end
  end

  def edit
    redirect_to :back unless current_user.can_edit?(@comment)
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def create
    @reply_notification = Notification.new

    if params[:comment][:parent_id].to_i > 0
      parent = Comment.find_by_id(params[:comment].delete(:parent_id))
      @comment = parent.children.build(comment_params)
      @reply_notification.user_id = parent.user_id
    else
      @comment = Comment.new(comment_params)
      @reply_notification.user_id = @comment.convo.user_id
    end
    @comment.user_id = current_user.id if current_user

    respond_to do |format|
      if @comment.save
        @convo = @comment.convo

        @comment.upvote(current_user)

        redirect_path = convo_slug_path(@convo.topic.slug, @convo.id, @convo.slug, anchor: "comment-#{@comment.id}")

        @reply_notification.message = \
          "someone replied to your #{ @comment.parent_id ? 'comment on' : 'convo' } <a href='#{redirect_path}'>"\
          "#{@comment.convo.title}</a>.".html_safe
        @reply_notification.save unless @reply_notification.user_id == current_user.id

        @commenters = @comment.convo.commenters - [current_user, @comment.convo.user]
        if @commenters.any? && @comment.parent_id.nil?
          @commenters.each do |commenter|
            Notification.create(
              user: commenter,
              message:  \
                "someone also commented on <a href='#{redirect_path}'>"\
                "#{@comment.convo.title}</a>.".html_safe
              )
          end
        end

        format.html { redirect_to redirect_path }
        format.json { render :show, status: :created, location: @comment }
      end
    end
  end

  def upvote
    @comment.upvote(current_user)
    render json: { message: "Successfully delivered" }, status: 201
  end
  def downvote
    @comment.downvote(current_user)
    render json: { message: "Successfully delivered" }, status: 201
  end

  def report
    @comment.report(convo_slug_path(@comment.convo.topic.slug, @comment.convo.id, @comment.convo.slug, anchor: "comment-#{@comment.id}"))
    render json: { message: "Successfully delivered" }, status: 201
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.edited = true
    
    if @comment.update(comment_params)
      redirect_to convo_path(@comment.convo)
    else
      render 'edit'
    end 
  end

  def destroy
    if current_user.can_edit?(@comment)
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to :back }
        format.json { head :no_content }
      end
    else
      redirect_to :back
    end
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:author, :comment, :convo_id, :parent_id, :points, :by_admin)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments, sort_by_attribute)
    comments.sort_by{|k, v| k[sort_by_attribute] }.reverse.map do |comment, nested_comments|
      render(comment) + 
      content_tag(:div, 
      	render(partial: 'comments/form', locals: { comment: Comment.new(parent_id: comment.id, convo_id: comment.convo.id), submit_text: 'reply', placeholder: 'reply to comment...', form_id: "reply_to_#{comment.id}" }) + 
      	(nested_comments.size > 0 ? comments_tree_for(nested_comments, sort_by_attribute) : nil), 
      	class: "replies")
    end.join.html_safe
  end
end

app/views/comments/_comment.html.erb
<% unless @convo %>
  <p class="post-reference metadata">
    <span><%= comment.user == current_user ? 'you' : (comment.author.present? ? comment.author : 'someone') %> commented on <%= link_to comment.convo.title, convo_slug_path(comment.convo.topic.slug, comment.convo.id, comment.convo.slug), class: 'highlight' %></span>
  </p>
<% end %>
<article class="truncate-content comment convo<%= ' hidden' if comment.points < -5 %><%= " disabled" if current_user && current_user.voted_on?(comment) %><%= " upvoted" if current_user.voted_for?(comment) %>" id="comment-<%= comment.id %>">
  <%= markdown_content_for(comment.comment, current_user) %>
  <p class="metadata">
    <span class="vote-links">
      <%= link_to '', upvote_comment_path(comment), remote: true, 
        class: 'arrow upvote'+(' active' if current_user.voted_for?(comment)).to_s %>
      <%= link_to '', downvote_comment_path(comment), remote: true, 
        class: 'arrow downvote'+(' active' if current_user.voted_against?(comment)).to_s %>
    </span>
    <% if @convo %>
      <% from_reply_form ||= nil %>
      <% unless from_reply_form %>
        <a href="#reply_to_<%= comment.id %>" class="highlight show-reply-form">reply</a> <span class="separator"> |</span>
      <% end %>
    <% end %>
    <%= link_to pluralized_points_for(comment), 
      "#comment-#{comment.id}", title: 'Permalink to comment' %> <span class="separator">|</span>
    <%= link_to time_ago_in_words(comment.created_at)+' ago', 
      "#comment-#{comment.id}", title: 'Permalink to comment' %>
    <% if comment.edited? %>(edited)<% end %>
    <% if @convo %>
      by
      <% if comment.user == comment.convo.user %>
        <abbr class="op-tag" title="the author of the convo">
      <% end %>
        <% if comment.by_admin? %>
          <span class="admin-tag">admin</span>
        <% else %>
          <% if comment.author? %>
              <%= comment.author %>
          <% else %>
            <%= comment.user == comment.convo.user ? 'author' : 'someone' %>
          <% end %>
        <% end %>
      <% if comment.user == comment.convo.user %>
        </abbr>
      <% end %>
    <% end %>
    <% unless comment.user == current_user %>
   <span class="separator">|</span> <%= link_to 'report', report_comment_path(comment), remote: true, method: :post, class: 'report-link', data: { confirm: "Are you sure?" } %>
    <% end %>
    <% if current_user.can_edit?(comment) %>
     <span class="separator">|</span> <%= link_to 'edit', edit_comment_path(comment) %>
     <span class="separator">|</span> <%= link_to 'delete', comment, :method => :delete %>
    <% end %>
  </p>
</article>

app/views/comments/_form.html.erb
<%= form_for comment, html: {
  id: form_id, class: 'block-form comment-form',
  data: { 
    'form-data' => (@s3_direct_post.fields), 
    'url' => @s3_direct_post.url, 
    'host' => URI.parse(@s3_direct_post.url).host 
  } } do |f| %>
  <%= invisible_captcha %>
  
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :convo_id %>
  <%= f.hidden_field :parent_id %>
  <div class="field">
    <%= f.label :comment, 'message', class: 'redundant-label' %>
    <%= f.text_area :comment, placeholder: placeholder, :maxlength => 10000 %>
  </div>
  <div class="options">
    <%= f.label :author, 'sign it (optional)', class: 'redundant-label' %>
    <%= f.text_field :author, placeholder: '— sign it (optional)', style: 'marg' %>
    <%= f.submit submit_text %>
    <% if current_user.admin? %>
      <label class="by-admin"><%= f.check_box :by_admin %>flag as admin</label>
    <% end %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>edit comment</h1>

<%= render partial: 'form', locals: { comment: @comment, placeholder: 'leave a comment...', form_id: 'edit_comment', submit_text: 'save changes' } %>

<%= link_to 'back to convo', :back %>

app/views/comments/index.html.erb
<h1>all comments</h1>
<ul class="horizontal-menu _group">
  <li>sort by</li>
  <li><%= link_to 'recent', '?show=recent', class: ("active" if params[:show] != 'popular') %></li>
  <li><%= link_to 'popular', '?show=popular', class: ("active" if params[:show] == 'popular') %></li>
</ul>
<% if !@comments.blank? %>
  <%= render @comments %>
<% else %>
  no comments yet.
<% end %>
<%= paginate @comments %>