config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'convos#index'

  resources :users
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/yolo', to: 'sessions#create_for_test_user'
  get '/logout', to: 'sessions#destroy'

  get '/activity', to: 'users#show'
  get '/settings', to: 'users#edit'

  get '/about', to: 'static_pages#about'
  get '/tos', to: 'static_pages#tos'

  post '/poll/:poll_id/:id/vote', to: 'polls#vote', as: :vote_on_poll

  resources :topics

  get '/topics/:id/comments', to: 'topics#comments', as: :topic_comments


  resources :convos do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  get '/topics/:topic_slug/:id/:convo_slug', to: 'convos#show', as: :convo_slug

  get '/notifications', to: 'notifications#index'

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :convos
  validates :name, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy, :comments]

  def show
    @title = "#{@topic.name}"
    @new_convo = Convo.new
    @new_convo.topic = @topic
    if params[:show] == 'recent'
      @convos = @topic.convos.order('created_at DESC').page(params[:page]).per(25)
    else
      @convos = @topic.convos.order('weighted_score DESC').page(params[:page]).per(25)
    end

  end

  def comments
    @comments = 
      if params[:show] == 'popular'
        Comment.find_by_topic_id(@topic).order('weighted_score DESC').page(params[:page]).per(25)
      else
        Comment.find_by_topic_id(@topic).order('created_at DESC').page(params[:page]).per(25)
      end
  end

  private
    def set_topic
      @topic = Topic.friendly.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topics_list 
    topics = Topic.all
  end
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/comments.html.erb
<h1><%= @topic.name %></h1>
<%= render partial: 'convos/content_filters', locals: {
	browse_convos_path: topic_path(@topic),
	browse_comments_path: topic_comments_path(@topic)
	} %>
<% if !@comments.blank? %>
  <%= render @comments %>
<% else %>
  no comments yet.
<% end %>
<%= paginate @comments %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>topics <%= link_to '+ new', new_topic_path %></h1>

<table>
  <thead>
    <tr>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= link_to 'show', topic %></td>
        <td><%= link_to 'edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<% meta title: @title %>
<h1><%= @title %></h1>
<%= render partial: 'convos/form', locals: { convo: @new_convo, submit_text: '+ start a convo', timeout: true } %>
<%= render partial: 'convos/content_filters', locals: {
	browse_convos_path: topic_path(@topic),
	browse_comments_path: topic_comments_path(@topic)
	} %>
<%= render @convos %>
<%= paginate @convos %>