config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'convos#index'

  resources :users
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/yolo', to: 'sessions#create_for_test_user'
  get '/logout', to: 'sessions#destroy'

  get '/activity', to: 'users#show'
  get '/settings', to: 'users#edit'

  get '/about', to: 'static_pages#about'
  get '/tos', to: 'static_pages#tos'

  post '/poll/:poll_id/:id/vote', to: 'polls#vote', as: :vote_on_poll

  resources :topics

  get '/topics/:id/comments', to: 'topics#comments', as: :topic_comments


  resources :convos do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  get '/topics/:topic_slug/:id/:convo_slug', to: 'convos#show', as: :convo_slug

  get '/notifications', to: 'notifications#index'

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/convo.rb
class Convo < ActiveRecord::Base
  extend FriendlyId
  friendly_id :to_slug, use: [:slugged, :finders]

  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :convo, presence: true
  validates_exclusion_of :convo, :in => %w( viagra cialis levitra vardenafil )
  validates :topic, presence: true
  validates :user, presence: true

  before_save :handle_polls

  attr_accessor :img_url

  acts_as_voteable
  include VoteActions
  include Report
  include PollsHandler
  include ActionView::Helpers::SanitizeHelper

  def normalize_friendly_id(string)
    duplicates = Convo.where("slug like ?", "%#{super}%")
    if duplicates.any?
      super+"-#{('a'..'z').to_a[duplicates.count]}" 
    else
      super
    end
  end

  def to_slug
    @slug = title
    @slug.gsub!(/&\w*;/, '')
    @slug
  end

  def title
    # matches first HTML tag and uses its content as title
    # e.g. if convo.convo is `<p>Hello</p><p>How are you?</p>`
    # `convo.title` would result in `Hello`
    # TODO: what if convo starts with image/multimedia? (use `alt`?)
    
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)

    @title = strip_tags(markdown.render(convo.gsub(/\n.*$/, '')))

    if @title.blank?
      'untitled'
    else
      Redcarpet::Render::SmartyPants.render(@title).html_safe.truncate(70)
    end
  end

  def thumbnails
    # TODO: this may be replaced with a more fancy shit
    /https?:\/\/.*\.(png|gif|jpg|jpeg)/.match(convo).to_a
  end

  def commenters
    comments.map(&:user).uniq
  end

  def self.search(search)
    if search
      where("title LIKE ? OR comment LIKE ?", "%#{search}%", "%#{search}%")
    else
      all
    end
  end

  def handle_polls
    polls_handler(convo)
  end

  $our_epoch = Time.local(2015, 1, 1, 1, 1, 1).to_time

  def epoch_seconds(t)
    (t.to_i - $our_epoch.to_i).to_f
  end

  def update_popularity
    s = points
    displacement = Math.log( [s.abs, 1].max,  10 )

    sign = if s > 0
      1
    elsif s < 0
      -1
    else
      0
    end

    result = (displacement * sign.to_f * 10) + ( epoch_seconds(created_at) / 45000 )
    self.update_attribute(:weighted_score, result)
  end

end

app/controllers/convos_controller.rb
class ConvosController < ApplicationController
  before_action :set_convo, only: [:show, :edit, :update, :destroy, :upvote, :downvote, :report]
  
  invisible_captcha only: [:create, :update]

  def index
    @new_convo = Convo.new

    if params[:show] == 'recent'
      @convos = Convo.order('created_at DESC').page(params[:page]).per(25)
    else
      @convos = Convo.order('weighted_score DESC').page(params[:page]).per(25)
    end
    if params[:search]
      @title = "search results for #{params[:search]}"
      @convos = Convo.search(params[:search]).order('created_at DESC').page(params[:page]).per(25)
    end
  end

  def show
    if params[:show].present?
      if params[:show] == 'recent'
        @comments_order = 'created_at'
      end
    else
      @comments_order = 'weighted_score'
    end
    @comments = @convo.comments.hash_tree
    @comment = Comment.new(convo: @convo)
    @comment_to_comment = Comment.new(convo: @convo, parent_id: params[:parent_id])
  end

  def edit
    redirect_to :back unless current_user.can_edit?(@convo)
  rescue ActionController::RedirectBackError
    redirect_to root_path
  end

  def upvote
    @convo.upvote(current_user)
    render json: { message: "Successfully delivered" }, status: 201
  end
  def downvote
    @convo.downvote(current_user)
    render json: { message: "Successfully delivered" }, status: 201
  end

  def report
    @convo.report(convo_slug_path(@convo.topic.slug, @convo.id, @convo.slug))
    render json: { message: "Successfully delivered" }, status: 201
  end

  def create
    if current_user.can_post_new_convo?
      @convo = Convo.new(convo_params)
      @convo.user_id = current_user.id if current_user

      respond_to do |format|
        if @convo.save
          @convo.upvote(current_user)
          format.html { redirect_to root_url(show: 'recent', convo: @convo.id) }
          # TO DO: fix this so it works as expected from topic view
          format.json { render :show, status: :created, location: @convo }
        else
          format.html { render :new }
          format.json { render json: @convo.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to root_path
    end
  end

  def update
    @convo.edited = true
    
    if @convo.update(convo_params)
      redirect_to @convo
    else
      render 'edit'
    end 
  end

  def destroy
    if current_user.can_edit?(@convo)
      @convo.destroy
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    def set_convo
      @convo = Convo.friendly.find(params[:id])
    end

    def convo_params
      params.require(:convo).permit(:convo, :author, :topic_id, :points, :by_admin)
    end
end

app/helpers/convos_helper.rb
module ConvosHelper
  def host_for(url)
    encoded_url = URI.encode(url)
    @host = URI.parse(encoded_url).host
    @host.slice!('www.')
    @host
  end
  def convo_url(convo, &options)
    convo_slug_path(convo.topic.slug, convo.id, convo.slug, &options)
  end
end

app/views/convos/_content_filters.html.erb
<nav class="content-filters _group">
	<ul class="horizontal-menu" style="float: left;">
		<li>sort by</li>
		<li><%= link_to 'popular', '?show=popular', class: ("active" if params[:show] != 'recent') %></li>
		<li><%= link_to 'recent', '?show=recent', class: ("active" if params[:show] == 'recent') %></li>
	</ul>
	<ul class="horizontal-menu" style="float: right;">
		<li>browse</li>
		<li><%= link_to 'convos', browse_convos_path + (params[:show] ? '?show='+params[:show].to_s : ''), class: ("active" if cp(browse_convos_path)) %></li>
		<li><%= link_to 'comments', browse_comments_path + (params[:show] ? '?show='+params[:show].to_s : ''), class: ("active" if cp(browse_comments_path)) %></li>
	</ul>
</nav>

app/views/convos/_convo.html.erb
<% if cp(activity_path) %>
  <p class="post-reference metadata">
    <span>you started a convo</span>
  </p>
<% end %>
<article class="<%= 'active ' if params[:convo].to_i == convo.id %><%= @convo ? 'single-convo' : 'convo truncate-content' %> _group<%= ' disabled' if current_user.voted_on?(convo) %><%= ' upvoted' if current_user.voted_for?(convo) %><%= ' hidden' if convo.points < -5 && !@convo %>">
  <% if convo.thumbnails.any? && !@convo %>
    <a 
      class="thumbnail" 
      href="<%= convo.thumbnails.first %>"
      style="background-image: url('<%= convo.thumbnails.first %>');" >
      <%= image_tag convo.thumbnails.first, style: 'display: none' %>
    </a>
  <% end %>
  <%= markdown_content_for(convo.convo, current_user) %>
  <p class="metadata">
    <span class="vote-links">
      <%= link_to '', upvote_convo_path(convo), remote: true, 
        class: 'arrow upvote'+(' active' if current_user.voted_for?(convo)).to_s %>
      <%= link_to '', downvote_convo_path(convo), remote: true, 
        class: 'arrow downvote'+(' active' if current_user.voted_against?(convo)).to_s %>
    </span>
    <%= link_to_unless @convo, pluralized_points_for(convo), convo_slug_path(convo.topic.slug, convo.id, convo.slug) %> <span class="separator">|</span>
    <% unless @convo || convo.comments.blank? %>
      <%= link_to pluralized_comments_for(convo), convo_slug_path(convo.topic.slug, convo.id, convo.slug) %> <span class="separator">|</span>
    <% end %>
    <% unless @convo %>
      <%= link_to 'reply', "#reply_to_convo_#{convo.id}", class: 'show-reply-form' %> <span class="separator">|</span>
    <% end %>
    <%= link_to_unless @convo, (time_ago_in_words convo.created_at)+' ago', convo_slug_path(convo.topic.slug, convo.id, convo.slug) %>
    <% if convo.edited? %>(edited)<% end %>
    <% unless cp(activity_path) %>
      by 
      <% if convo.by_admin? %>
        <span class="admin-tag">admin</span>
      <% else %>
        <% if convo.author? %>
          <%= convo.author %>
        <% else %>
          <% if current_user.admin? and convo.user.admin? %>
            <span class="admin-tag"><%= convo.user.username %></span>
          <% else %>
            someone
          <% end %>
        <% end %> 
      <% end %>
    <% end %>
    <% unless @topic %>
      <% if convo.topic %>
        in <%= link_to convo.topic.name, topic_path(convo.topic) %>
      <% end %>
    <% end %>
    <% unless convo.user == current_user %>
    <span class="separator">|</span> <%= link_to 'report', report_convo_path(convo), remote: true, method: :post, class: 'report-link', data: { confirm: "Are you sure?" } %>
    <% end %>
    <% if current_user.can_edit?(convo) %>
      <span class="separator">|</span> <%= link_to 'edit', edit_convo_path(convo) %> 
      <span class="separator">|</span> <%= link_to 'delete', convo, :method => :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </p>
</article>
<% unless @convo %>
  <div class="replies">
    <%= render partial: 'comments/form', locals: { comment: Comment.new(convo_id: convo.id), submit_text: 'submit', placeholder: 'leave a comment...', form_id: "reply_to_convo_#{convo.id}" } %>
  </div>
<% end %>

app/views/convos/_form.html.erb
<%= form_for convo, html: { class: 'block-form', 
  data: { 
    'form-data' => @s3_direct_post.fields, 
    'url' => @s3_direct_post.url, 
    'host' => URI.parse(@s3_direct_post.url).host 
  } } do |f| %>
  <%= invisible_captcha %>

  <% if convo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convo.errors.count, "error") %> prohibited this convo from being saved:</h2>

      <ul>
      <% convo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :convo, 'message', class: 'redundant-label' %>
    <%= f.text_area :convo, placeholder: 'what’s on your mind?', :maxlength => 10000 %>
  </div>

  <div class="options">

    <div class="select">
      in
      <ul class="nicer-select">
        <% for topic in topics_list %>
          <li><a href data-id=<%= topic.id %>><%= topic.name %></a></li>
        <% end %>
      </ul>
      <%= f.hidden_field :topic_id %>
    </div>
    <script>
      $('.nicer-select').each(function(){
        var self = this;
        var targetField = $('#convo_topic_id');
        var currentValue = function(){
          var topicId = $(targetField).val();
          if (topicId) {
            return $('a[data-id='+($(targetField).val())+']', self).text();
          } else {
            return 'choose a topic <span>(required)</span>';
          };
        };
        var newshit = $('<a href>');
        newshit.html(currentValue());
        $(self).before(newshit);
        $(self).hide();
        $('a[data-id]', self).on('click', function(){
          event.preventDefault();
          $(targetField).val($(this).attr('data-id'));
          currentValue = $(this);
          newshit.text(currentValue.text());
          $(self).hide();
        });
        $(window).on('click', function(){
          $(self).hide();
        })
        newshit.on('click', function(){
          event.preventDefault();
          event.stopPropagation ();
          $(self).toggle();
        });
      });
      $('#new_convo').submit(function(event){
        if ($('#convo_convo').val().match(/^\s*$/)) {
          event.preventDefault();
          alert('This can’t be empty.')
        } else if ($('#convo_topic_id').val() == ''){
          event.preventDefault();
          alert('Please choose a topic.')
        }
      });
    </script>
    <%= f.label :author, 'sign it (optional)', class: 'redundant-label' %>
    <%= f.text_field :author, placeholder: '— sign it (optional)' %>
    <%= f.submit submit_text, timeout: ((current_user.convos.last.created_at.to_f*1000) unless current_user.can_post_new_convo?), id: 'submit_convo' %>
    <% if timeout %>
      <script>
        $('[timeout]').each(function(){
          var $self = $(this);
          var timeout = $self.attr('timeout');
          var originalVal = $self.val();
          var dateThen = new Date(parseInt(timeout));
          var dateNow = new Date();
          var timeLeft = function(){
            return Math.round((dateThen.getTime()-dateNow.getTime()+60000)/1000) 
          };

          $self.val('wait '+timeLeft()+'s');
          $self.attr('disabled', 'disabled');

          var timer = setInterval(function(){
            dateNow = new Date();
            timeLeft();
            if (timeLeft() < 60 && timeLeft() >= 1){
              $self.val('wait '+timeLeft()+'s');
            } else {
              $self.val(originalVal);
              $self.removeAttr('disabled');
              clearInterval(timer);
            };
          }, 1000);
        });
      </script>
    <% end %>
    <% if current_user.admin? %>
      <label class="by-admin"><%= f.check_box :by_admin %>flag as admin</label>
    <% end %>
  </div>
  <!-- <a class="formatting-link" href="http://www.convos.org/topics/feedback/135/formatting" target="_blank">formatting help</a> -->
<% end %>

app/views/convos/edit.html.erb
<h1>edit convo</h1>

<%= render partial: 'form', locals: { convo: @convo, submit_text: 'save changes', timeout: false } %>

<%= link_to 'back to convo', @convo %> |
<%= link_to 'back to homepage', root_path %>

app/views/convos/index.html.erb
<% flash.each do |key, value| %>
	<aside class="alert alert-<%= key %>"><%= value %></aside>
<% end %>
<%= render partial: 'form', locals: { convo: @new_convo, submit_text: '+ start a convo', timeout: true } %>
<%= render partial: 'convos/content_filters', locals: {
	browse_convos_path: root_path,
	browse_comments_path: comments_path
	} %>
<% cache(["convos_index", @convos.map(&:id), @convos.maximum(:updated_at)]) do %>
	<% @convos.each do |convo| %>
		<% cache([current_user, convo]) do %>
			<%= render partial: 'convo', locals: { convo: convo } %>
		<% end %>
	<% end %>
<% end %>
<%= paginate @convos %>

app/views/convos/new.html.erb
<h1>start a convo</h1>

<%= render partial: 'form', locals: { convo: @convo } %>

app/views/convos/show.html.erb
<% meta title: @convo.title %>
<p id="notice"><%= notice %></p>
<%= render @convo %>

<section class="comments">
  <% if @comments.any? %>
    <h2><%= pluralized_comments_for @convo %></h2>
  <% end %>
  <%= render partial: 'comments/form', locals: { comment: @comment, submit_text: 'submit', placeholder: 'leave a comment...', form_id: 'new_comment' } %>
  <% if @comments.any? %>
    <ul class="horizontal-menu _group">
      <li>sort by</li>
      <li><%= link_to 'top', '?show=top', class: ("active" if params[:show] != 'recent') %></li>
      <li><%= link_to 'recent', '?show=recent', class: ("active" if params[:show] == 'recent') %></li>
    </ul>
    <%= comments_tree_for @comments, @comments_order %>
  <% end %>
</section>