config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'convos#index'

  resources :users
  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/yolo', to: 'sessions#create_for_test_user'
  get '/logout', to: 'sessions#destroy'

  get '/activity', to: 'users#show'
  get '/settings', to: 'users#edit'

  get '/about', to: 'static_pages#about'
  get '/tos', to: 'static_pages#tos'

  post '/poll/:poll_id/:id/vote', to: 'polls#vote', as: :vote_on_poll

  resources :topics

  get '/topics/:id/comments', to: 'topics#comments', as: :topic_comments


  resources :convos do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  get '/topics/:topic_slug/:id/:convo_slug', to: 'convos#show', as: :convo_slug

  get '/notifications', to: 'notifications#index'

  resources :comments do
    member do
      get 'upvote'
      get 'downvote'
      post 'report'
    end
  end

  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />

		<%= metamagic site: "convos", title: [:title, :site], separator: " | ",
			description: "An anonymous message board. Share your thoughts, comment and vote. No registration required.",
			keywords: %w(anonymous forum reddit 4chan alternative) %>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<link href="https://fonts.googleapis.com/css?family=Lato:400,400italic,700,700italic" rel="stylesheet" />
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>

		<!-- ios/mobile shiz -->
		<meta name="viewport" content="width=device-width">
		<meta name="apple-mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-status-bar-style" content="default">
		<link rel="apple-touch-icon" href="<%= asset_path 'logo.png' %>">

		<script>
			(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			ga('create', 'UA-72648001-1', 'auto');
		</script>
	</head>
	<body>
		<nav class="user-links metadata">
			<%= unread_notifications_link %>
			<% if current_user.guest? %>
				<%= link_to "log in", login_path %> <span class="separator">|</span>
				<%= link_to "sign up (optional)", signup_path, class: 'highlight' %>
			<% else %>
				<!-- <a href='/activity'>hello, <strong><%= current_user.email %></strong> (<%= current_user.total_points %>)</a> <span class="separator">|</span>  -->
				<a href='/activity'>my activity (<%= current_user.total_points %>)</a> <span class="separator">|</span> 
				<%= link_to "settings", settings_path %> <span class="separator">|</span>
				<%= link_to "logout", logout_path %>
			<% end %>
		</nav>
		<main>
			<%= link_to image_tag('logo.png', alt:'convos'), root_path, class:'logo' %>
			<% if current_user.guest? && cp(root_path) %>
				<p class="site-headline">the anonymous newsfeed anyone can post to.</p>
			<% end %>
			<nav class="topic-tabs">
				<%= link_to "all topics", root_path, class: cp(root_path) %>
				<% for topic in topics_list %>
					<%= link_to topic.name, topic_path(topic, show: params[:show]), class: cp(topic_path(topic)) %>
				<% end %>
				<hr>
				<%= link_to "convos on Twitter", "https://twitter.com/convosorg", :target => "_blank" %>

				<% if current_user.is_test_user? %>
					<%= form_tag '/yolo' do |f| %>
						<%= collection_select(:user, :id, User.test_users, :id, :email,	{ selected: current_user.id}) %>
						<%= submit_tag "submit" %>
					<% end %>
				<% end %>
			</nav>
			<%= yield %>
		</main>
		<footer class="site-footer">
			<p class="copyright">&copy; 2016. all rights reserved. <a href="/tos" style="float: right;">terms of service</a></p> 
		</footer>
	</body>
</html>